apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: keyvaultidentity
spec:
  type: 0
  ResourceID: $ID$
  ClientID: $CLIENTID$
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: keyvaultidentitybinding
spec:
  AzureIdentity: keyvaultidentity
  Selector: keyvaultidentity