<<<<<<< HEAD
<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
      name: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registry3m84331.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: SQL_USER
          value: sqladmin3M84331        
        - name: SQL_PASSWORD
          value: sO7z53Sy8
        - name: SQL_SERVER
          value: sqlserver3m84331.database.windows.net
        - name: ASPNETCORE_ENVIRONMENT
          value: Production   
        - name: USER_API_ENDPOINT
          value: http://userprofile.default.svc.cluster.local
        - name: TRIPS_API_ENDPOINT
          value: http://trips.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tripviewer
=======
=======
>>>>>>> 2888297adbd844c9c9a3bb226d31dd78c7ccad06
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
      name: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registry3m84331.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: SQL_USER
          value: sqladmin3M84331        
        - name: SQL_PASSWORD
          value: sO7z53Sy8
        - name: SQL_SERVER
          value: sqlserver3m84331.database.windows.net
        - name: ASPNETCORE_ENVIRONMENT
          value: Production   
        - name: USER_API_ENDPOINT
          value: http://userprofile.default.svc.cluster.local
        - name: TRIPS_API_ENDPOINT
          value: http://trips.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tripviewer
<<<<<<< HEAD
>>>>>>> 2888297adbd844c9c9a3bb226d31dd78c7ccad06
=======
>>>>>>> 2888297adbd844c9c9a3bb226d31dd78c7ccad06
  type: LoadBalancer