apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tripviewer-api-gateway
  namespace: api
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "table4-openhack.southcentralus.cloudapp.azure.com"      
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tripviewer-web-gateway
  namespace: web
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "table4-openhack.southcentralus.cloudapp.azure.com"      
