apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
    aadpodidbinding: keyvaultidentity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
        aadpodidbinding: keyvaultidentity        
      name: userprofile
    spec:
      containers:
      - name: userprofile
        image: registry3m84331.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secrets
        flexVolume:
          driver: "azure/kv"
          options:
            usepodidentity: "true"                   # [OPTIONAL] if not provided, will default to "false"
            keyvaultname: "$KEYVAULTNAME$"              # [REQUIRED] the name of the KeyVault
            keyvaultobjectnames: "SQL-USER;SQL-PASSWORD;SQL-SERVER"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"      # [OPTIONAL] list of KeyVault object aliases
            keyvaultobjecttypes: "secret;secret;secret"               # [REQUIRED] list of KeyVault object types: secret, key, cert
            resourcegroup: "$RESOURCEGROUP$"        # [REQUIRED] the resource group of the KeyVault
            subscriptionid: "$SUBSCRIPTION$"                 # [REQUIRED] the subscription ID of the KeyVault
            tenantid: "$TENANT$"                    # [REQUIRED] the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: userprofile
  type: LoadBalancer