apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
      name: trips
    spec:
      containers:
      - name: trips
        image: registry3m84331.azurecr.io/tripinsights/trips:1.0
        env:
        - name: SQL_USER
          value: sqladmin3M84331        
        - name: SQL_PASSWORD
          value: sO7z53Sy8
        - name: SQL_SERVER
          value: sqlserver3m84331.database.windows.net
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: OPENAPI_UI_URI
          value: http://changeme
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: trips
  type: LoadBalancer